services:
  ollama-service:
    image: ollama/ollama:0.1.27
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      # Ollama is running in a container without GPU
    volumes:
      - ../ollama:/root/.ollama
    ports:
      - 11434:11434


